" Source: https://github.com/changemewtf/no_plugins
" BASIC SETUP:

set nocompatible              " don't act like vi

set number                    " line numbers
set relativenumber            " relative line numbers
set ruler                     " cursor coordinates
set showcmd                   " show partial commands in bottom right
" set hlsearch                  " highlight search results
set nohlsearch                " disable search result highlights

set wrap lbr                  " linebreak on word boundaries

" convert tabs to spaces and set width
set expandtab                 " use spaces instead of real tab characters
set tabstop=2                 " how many spaces a literal \t looks like (purely visual)
set softtabstop=2             " insert/delete 2 spaces per tab key
set shiftwidth=2              " indent/outdent by 2 spaces using `>>`/`<<`
set sts=4

""" show invisible chars
" set list

" highlight line with cursor
"set cursorline
":highlight CursorLine ctermbg=grey

" enable syntax and plugins (for netrw)
syntax enable
filetype plugin on

" FINDING FILES:
" - hit tab to :find by partial match
" - use * to make it fuzzy
" - :b lets you autocomplete any open buffer

" Search down into subfolers
" Provides tab-completion for all file-related tasks
set path+=**

" Display all matching files when we tab complete
set wildmenu

" TAG JUMPING:
" - ^] to jump to tag under cursor
" - g^] for ambiguous tags
" - ^t to jump back up the tag stack

" Create the `tags` file (may need to install ctags first)
command! MakeTags !ctags -R .

" AUTOCOMPLETE: (:help ins-completion)
" - ^x^n for just this file
" - ^x^f for  filenames (works w/ path option)
" - ^x^] for nane
" - ^n for anything specified by the 'complete' option
" - ^n and ^p to go back forth in the suggestion list

" FILE BROWSING: (:help netrw-browse-maps)
" - :edit a folder to open a file browser
" - <CR>/v/t to open in an h-split/v-split/tab

let g:netrw_banner=0          " disable banner
let g:netrw_browse_split=4    " open in prior window
let g:netrw_altv=1            " open splits to the right
let g:netrw_liststyle=3       " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" SNIPPETS:

" Read an empty HTML template and move cursor to title
nnoremap ,html :-1read $HOME/.vim/.skeleton.html<CR>3jwf>a

