colors:
  body: none
  date: black
  tags: yellow
  title: cyan
default_hour: 9
default_minute: 0
editor: nvim -c startinsert
encrypt: true
highlight: true
indent_character: '|'
journals:
  default:
    journal: /Users/vieuler/wd/prsnl-notes/jrnl/journal.txt
linewrap: 79
tagsymbols: '#@'
template: false
timeformat: '%F %r'
version: v4.1
