# add -shell-escape if using `minted` package for code highlighting. WARN: security risk
# only use on trusted .tex files
$pdflatex = "pdflatex -file-line-error -halt-on-error -interaction=nonstopmode -synctex=1";
