#!/usr/bin/env bash
# fzf in working directory and open a tmux session for selected repo: theprimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/wd/playground ~/wd/mkspc ~/wd/rmd ~/wd/ ~/ -mindepth 1 -maxdepth 1 -type d | fzf --tmux 80%,50%)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name="$(basename "$selected" | tr . -)"

if [[ -z $TMUX ]]; then
    tmux new-session -As "$selected_name" -c "$selected"
    exit 0
fi

tmux new-session -Ads "$selected_name" -c "$selected"
tmux switch-client -t "$selected_name"

