#!/usr/bin/env bash

# Get repo root path - not necessary
# REPO_ROOT="$(git rev-parse --show-toplevel)"

# Iff run.m4 is staged for commit
if git diff --cached --name-only | rg "run.m4$"; then
    # Generate the run script from run.m4
    argbash "run.m4" -c -o "run"

    # Add run script to the commit
    git add "run"
fi
