#!/usr/bin/env bash

# Navigate to the repository root
REPO_ROOT="$(git rev-parse --show-toplevel)"

# Iff run.m4 is staged for commit
if git diff --cached --name-only | rg "run.m4$"; then
    # Generate the run script from setup.m4
    argbash "$REPO_ROOT/run.m4" -o "$REPO_ROOT/run"

    # Add run script to the commit
    git add "$REPO_ROOT/run"
fi
